apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudycode-uat-data
  namespace: cloudycode-uat
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
