apiVersion: v1
kind: Pod
metadata:
  name: bot-pod-example
  namespace: default
spec:
  serviceAccountName: pod-creator-bot
  containers:
    - name: worker
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
        requests:
          cpu: "250m"
          memory: "64Mi"
